spring:
  datasource:
    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    username: S08P31S101
    password: DidIP0GxNb
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  data:
    mongodb:
      uri: mongodb+srv://S08P31S101:J7C78fYHve@ssafy.ngivl.mongodb.net/S08P31S101?authSource=admin
    
  jpa:
    defer-datasource-initialization: true
      
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret: hello.world.ee.ff