spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  data:
    mongodb:
      uri: mongodb://k8s1011.p.ssafy.io:20000/
      database: wonik


  jpa:
    defer-datasource-initialization: true
      
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600
