spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  data:
    mongodb:
      host: 3.36.125.122
      port: 27017
      authentication-database: admin
      database: ﻿admin
      username: ssafy
      password: ssafy1111
        
  jpa:
    defer-datasource-initialization: true
      
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret: hello.world.ee.ff