spring:
  datasource:
    url: jdbc:mariadb://54.180.202.20/wonik
    username: ssafy
    password: ssafy1111
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    mongodb:
      uri: mongodb+srv://S08P31S101:J7C78fYHve@ssafy.ngivl.mongodb.net/S08P31S101?authSource=admin
    
  jpa:
    defer-datasource-initialization: true
      
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  token:
    secret: hello.world.ee.ff