spring:
  datasource:
    jdbc-url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P31S101?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P31S101
    password: DidIP0GxNb
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    mongodb:
      uri: mongodb+srv://S08P31S101:J7C78fYHve@ssafy.ngivl.mongodb.net/S08P31S101?authSource=admin
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    